FROM  buildpack-deps:focal


# Install custom tools, runtime, etc.
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - \
    && apt-get update \
    && curl -sLO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl \
    && mv kubectl /usr/local/bin/kubectl && chmod 755 /usr/local/bin/kubectl \
    && wget -q https://get.helm.sh/helm-v3.2.4-linux-amd64.tar.gz \
    && tar zxf helm-v3.2.4-linux-amd64.tar.gz \
    && mv linux-amd64/helm /usr/local/bin/helm3 \
    && chmod 755 /usr/local/bin/helm3 \
    && wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb  \
    && apt-get -y install \
            software-properties-common \
            shellcheck \
            apt-transport-https \
            ca-certificates \
            curl \
            software-properties-common \
            ./google-chrome-stable_current_amd64.deb \
    && add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) \
      stable" \
   && apt-get -y install docker-ce \
   && rm -rf /var/lib/apt/lists/* 

# Apply user-specific settings
# Refresh on 2021-01-28




